# Copyright (c) 2026 Ilya Snegov (aka Sierra Arn)

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# packages/shared/src/postgres_lib/models/inference_history.py
from sqlalchemy import ForeignKey, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column
from .base import Base


class InferenceHistory(Base):
    """
    Represents a completed model run submitted by an authenticated user.

    Attributes
    ----------
    user_id : Mapped[int]
        Foreign key referencing the user who submitted the request.
        Indexed to accelerate per-user history queries.
    input_text : Mapped[str]
        The raw text submitted by the user as the model prompt.
    output_text : Mapped[str]
        The text generated by the model in response to the prompt.

    Notes
    -----
    Both input_text and output_text are declared as Text (unbounded)
    rather than String(n) because prompt and generation length cannot
    be bounded in advance without truncating valid content.
    """

    __tablename__ = "inference_history"

    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="References the authenticated user who submitted the request",
    )
    input_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Raw text submitted by the user as the model prompt",
    )
    output_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Text generated by the model in response to the prompt",
    )
