"""Auto migration

Revision ID: b5dabad9f8b0
Revises: 
Create Date: 2026-07-10 09:02:35.393267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5dabad9f8b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('name', sa.String(length=120), nullable=False, comment='Full name provided by the visitor for follow-up communication'),
    sa.Column('email', sa.String(length=254), nullable=False, comment='Contact email address; max 254 characters per RFC 5321; not unique to allow repeat enquiries'),
    sa.Column('message', sa.Text(), nullable=False, comment='Free-form text describing the intended use case or project requirements'),
    sa.Column('company', sa.String(length=120), nullable=True, comment='Optional organization or company name'),
    sa.Column('status', sa.Enum('new', 'in_progress', 'answered', 'rejected', name='lead_status'), server_default='new', nullable=False, comment='Current follow-up state of the collaboration request'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False, comment='Unique email address; max 254 characters per RFC 5321'),
    sa.Column('hashed_password', sa.String(length=60), nullable=False, comment='Bcrypt hash of the user password; bcrypt output is always exactly 60 characters'),
    sa.Column('role', sa.Enum('unauthenticated', 'user', 'moderator', 'admin', name='role'), server_default='user', nullable=False, comment='Access level and permissions of the user'),
    sa.Column('inference_runs_count', sa.Integer(), server_default='0', nullable=False, comment='Total number of model inference runs made by this user'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('inference_history',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='References the authenticated user who submitted the request'),
    sa.Column('input_text', sa.Text(), nullable=False, comment='Raw text submitted by the user as the model prompt'),
    sa.Column('output_text', sa.Text(), nullable=False, comment='Text generated by the model in response to the prompt'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_history_user_id'), 'inference_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inference_history_user_id'), table_name='inference_history')
    op.drop_table('inference_history')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('leads')
    # ### end Alembic commands ###
