# Copyright (c) 2026 Ilya Snegov (aka Sierra Arn)

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# packages/server/src/server/modules/inference/pages.py
from fasthtml.common import Div, H2, P, FT
from postgres_lib import Role
from .partials import create_inference_form_partial
from ...shared import create_icon
from ...shared.ui import create_layout


def _create_page_header() -> Div:
    """
    Create the introductory header for the inference page.

    Displays a title and a brief description explaining the purpose
    of the inference interface to the user.

    Returns
    -------
    Div
        FastHTML container holding the heading and descriptive paragraph,
        styled for visual hierarchy and proper spacing above the form.
    """
    return Div(
        H2(
            create_icon("sparkles", size=28, cls="inline-block mr-2 align-middle"),
            "Model Inference",
            cls="text-2xl font-bold mb-2",
        ),
        P(
            "Submit a text prompt and receive a response generated by the model.",
            cls="text-base-content/60 mb-8",
        ),
    )


def create_inference_page(
    role: Role = Role.USER,
    error: str | None = None,
) -> FT:
    """
    Create the inference page with a prompt submission form and a
    result container populated via HTMX polling.

    The form itself is rendered via create_inference_form_partial so that
    the same markup is reused both on initial page load and in HTMX
    partial responses, avoiding duplication.

    The form posts to /inference which enqueues a Celery task and
    returns a spinner partial with a polling trigger. The spinner is
    rendered inside the result container and replaced by the final
    output once the task completes.

    The result container is initially empty and becomes visible only
    after the first submission. Subsequent submissions replace the
    previous result. The submit button is disabled while a task is
    running to prevent duplicate submissions.

    Parameters
    ----------
    role : Role
        Resolved access role of the current user. Passed to the global
        layout to determine which navigation links are displayed.
        Default is USER since this page requires authentication.
    error : str or None
        Optional error message string. When provided, it is passed
        to the inference form partial to display a validation or
        quota failure alert. Default is None.

    Returns
    -------
    FT
        Fully assembled FastHTML document containing the complete
        inference page layout.
    """
    return create_layout(
        Div(
            _create_page_header(),
            create_inference_form_partial(error=error),
            cls="max-w-3xl mx-auto py-8",
            **{"x-data": "{ running: false }"},
        ),
        title="Inference",
        role=role,
    )